server:
  port: 9999
  servlet:
    context-path: /jpa
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: springboot-jpa-demo
  datasource:
    url: jdbc:mysql://localhost:3306/poc?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    show-sql: true
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        session_factory:
#          statement_inspector: com.poc.tenant.inspector.SqlStatementInspector
  output:
    ansi:
      enabled: always
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr(%-80.80logger{79}){cyan} %clr(:){faint} %m%n'

#  level:
#    com.example.demo: debug
#debug: true
